spring:
  application:
    name: book

  profiles:
    active: default

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: debug

consumer:
  topic1:
    name: rental_rent
  topic2:
    name: rent_return
  groupId:
    name: overdue_clear