spring:
  application:
    name: rental

  profiles:
    active: default

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: debug

producers:
  bootstrap-servers: localhost:9092
  topic1:
    name: rental_rent
  topic2:
    name: rent_return
  topic3:
    name: overdue_clear
  topic4:
    name: point_use

consumer:
  topic1:
    name: rental_result
  groupId:
    name: rental